# C:/dev/robolog/docker-compose.yml

# ✨ 1. Define a custom network for your application stack
networks:
  robolog-net:
    driver: bridge

volumes:
  logs:           # central log files collected by Fluent Bit
  ollama:         # model cache for Ollama

services:
  # 👉 Main application with Nginx, Node, PM2
  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    depends_on:
      analyzer:
        # ✅ BEST PRACTICE: Wait for the dependency to be healthy, not just started.
        condition: service_healthy
    # ✅ BEST PRACTICE: Health check the full stack (Nginx SSL -> Next.js).
    # The -k flag is needed to handle the self-signed certificate.
    healthcheck:
      test: [ "CMD", "curl", "-fk", "https://localhost/api/health" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "80:80"   # For the HTTP -> HTTPS redirect
      - "443:443" # For the main HTTPS site
    environment:
      # ✅ BEST PRACTICE: Make frontend configuration portable via environment variables.
      - NEXT_PUBLIC_ANALYZER_WS_URL=http://localhost:9881
    networks: # ✨ 2. Add the service to your custom network
      - robolog-net

  # 👉 Ollama serving Gemma 3n (e2b)
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - ollama:/root/.ollama
    command: ["serve"]
    ports:
      - "11434:11434"
    networks: # ✨ 2. Add the service to your custom network
      - robolog-net

  # 👉 Fluent Bit – centralise all container logs into /logs/all.log
  fluent-bit:
    image: fluent/fluent-bit:3.0
    container_name: fluent-bit
    volumes:
      - logs:/logs
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "24224:24224"
    restart: unless-stopped
    networks: # ✨ 2. Add the service to your custom network
      - robolog-net

  # 👉 Log Analyzer – Node script that calls Gemma & posts to Discord
  analyzer:
    build: ./analyzer
    container_name: analyzer
    depends_on:
      ollama:
        condition: service_healthy # depends_on can be more specific
      fluent-bit:
        condition: service_started
    # ✅ BEST PRACTICE: Mount the host filesystem to get real disk usage data.
    # This makes the diskReport() function in the analyzer much more useful.
    volumes:
      - /:/host:ro
      - logs:/logs # This line was part of a duplicate key and has been merged.
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9880/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "9881:9881"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - MODEL_NAME=gemma3n:e2b
      - LANGUAGE=English
      # The analyzer now uses a single, clear variable for the optional initial webhook.
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PLATFORM=discord
    networks: # ✨ 2. Add the service to your custom network
      - robolog-net
